f = open("C:\\Users\sande\Documents\Python\Practice Code\email.csv","r")
strEmail = f.read()
x = strEmail.replace("\n",",")
# print(type(f.read()))
# print(x)
emailList = x.split(",")
print(type(emailList))
# print(emailList)
print(emailList[0])
# emaillist = list(f.read())
# print(emaillist)